apiVersion: v2
name: backstage
description: Helm chart for Backstage. Backstage is an open platform for building developer portals.
type: application
version: 0.11.0
appVersion: main
keywords:
  - backstage
home: https://backstage.io
icon: https://backstage.io/img/twitter-summary.png
sources:
  - https://github.com/backstage/backstage
  - https://github.com/mcwarman/backstage-sample-app
  - https://github.com/mcwarman/helm-charts
maintainers:
  - name: stvnksslr
    email: stvnksslr@gmail.com
