apiVersion: v2
appVersion: 1.12.95-6a720b79
dependencies:
- condition: ingress-nginx.enabled
  enabled: true
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.1.0
- condition: reloader.enabled
  name: reloader
  repository: https://stakater.github.io/stakater-charts
  version: v0.0.104
description: Development platform for Kubernetes applications
home: https://okteto.com
icon: https://okteto.com/okteto-symbol-circle-inverse-1.1.png
keywords:
- okteto
- development
- team collaboration
kubeVersion: '>=1.19.0-0'
maintainers:
- email: ramiro@okteto.com
  name: Ramiro Berrelleza
- email: pablo@okteto.com
  name: Pablo Chico de Guzman
- email: irespaldiza@okteto.com
  name: Iñaki Respaldiza
name: okteto-enterprise
version: 0.12.0
