apiVersion: v1
kind: Service
metadata:
  name: {{ include "backstage.appFullname" . }}
  labels:
    {{- include "backstage.appLabels" . | nindent 4 }}
  {{- with .Values.app.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.service.targetPort }}
      protocol: TCP

  selector:
    {{- include "backstage.appSelectorLabels" . | nindent 4 }}
