apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage.appFullname" . }}
  labels:
    {{- include "backstage.appLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "backstage.appSelectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "backstage.appSelectorLabels" . | nindent 8 }}
      {{- with .Values.app.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.dockerRegistrySecretName }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegistrySecretName }}
      {{- end}}
      serviceAccountName: {{ include "backstage.appServiceAccountName" . }}
      {{- with .Values.app.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: backstage
          {{- with .Values.app.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: {{ include "backstage.appImage" . }}
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            {{- if .Values.appConfig.app.title }}
            - name: APP_CONFIG_app_title
              value: {{ .Values.appConfig.app.title | quote }}
            {{- end }}
            {{- if .Values.appConfig.app.baseUrl }}
            - name: APP_CONFIG_app_baseUrl
              value: http://localhost:8080
            {{- end }}
            {{- if .Values.appConfig.backend.baseUrl }}
            - name: APP_CONFIG_backend_baseUrl
              value: {{ .Values.appConfig.backend.baseUrl | quote }}
            {{- end }}
            {{- if .Values.appConfig.organization.name }}
            - name: APP_CONFIG_organization_name
              value: {{ .Values.appConfig.organization.name | quote }}
            {{- end }}
            {{- with .Values.app.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          {{- with .Values.app.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
