{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "generic.fullname" . }}-cert
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ .Values.host }}
  secretName: {{ .Values.tlsSecretName }}
  issuerRef:
    name: {{ .Values.certificate.issuerRef.name }}
    kind: {{ .Values.certificate.issuerRef.kind }}
{{- end }}