{{- if and .Values.buildkit.enabled .Values.buildkit.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ include "okteto.buildkitname" . }}"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: "{{ include "okteto.buildkitname" . }}"
  minReplicas: {{ .Values.buildkit.hpa.min }}
  maxReplicas: {{ .Values.buildkit.hpa.max }}
  targetCPUUtilizationPercentage: {{ .Values.buildkit.hpa.cpu }}
{{- end }}
