{{- if .Values.buildkit.enabled }}
{{- if .Values.networkPolicies.enabled }}
apiVersion: {{ template "okteto.networkPolicies.apiVersion" . }}
kind: NetworkPolicy
metadata:
  name: "{{ include "okteto.fullname" . }}-buildkit"
spec:
  egress:
  - ports:
    - port: 53
      protocol: UDP
    to:
    - namespaceSelector:
        matchLabels:
          app.kubernetes.io/name: kube-system
      podSelector:
        matchLabels:
          k8s-app: kube-dns
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
          {{- range .Values.networkPolicies.blockedCIDRs }}
          - {{ . }}
          {{- end }}
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: ingress-nginx
          app.kubernetes.io/instance: {{ .Release.Name }}
          app.kubernetes.io/component: "controller"
  podSelector:
    matchLabels:
      app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-buildkit"
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "buildkit"
      app.kubernetes.io/part-of: "okteto"
  policyTypes:
  - Egress
{{- end }}
{{- end }}