{{- if .Values.registry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "okteto.fullname" . }}-registry-secret
  labels:
    app.kubernetes.io/component: "registry"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-registry-secret"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  haShared: {{ .Values.registry.haShared | b64enc | quote }}
{{- end }}