{{- if .Values.unsupported.billing.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "okteto.fullname" . }}-billing"
  labels:
    app.kubernetes.io/component: "billing"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-billing"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.unsupported.billing.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "billing"
        app.kubernetes.io/part-of: "okteto"
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "billing"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.podAnnotations }}
          annotations:
{{ toYaml .Values.podAnnotations | indent 12 }}
{{- end }}
        spec:
          serviceAccountName: {{ include "okteto.fullname" . }}
          {{- if .Values.tolerations.oktetoPool }}
          tolerations:
          - key: "okteto-node-pool"
            operator: "Equal"
            value: "{{ .Values.tolerations.oktetoPool }}"
            effect: "NoSchedule"
          nodeSelector:
            okteto-node-pool: "{{ .Values.tolerations.oktetoPool }}"
          {{- end }}
          volumes:
          - name: tls-certs
            secret:
              defaultMode: 420
              secretName: {{ include "okteto.ingress.tlsSecret" . }}
          restartPolicy: Never
          containers:
            - name: billing
              image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "expire-trials" ]
              envFrom:
              - configMapRef:
                  name: "{{ include "okteto.fullname" . }}"
              - secretRef:
                  name: {{ include "okteto.fullname" . }}
              - secretRef:
                  name: "{{ .Values.cloud.secret.name }}"
                  optional: true
              volumeMounts:
                - name: tls-certs
                  mountPath: /run/secrets/tls
                  readOnly: true
{{- end }}