{{- if .Values.cloud.provider.civo.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ include "okteto.fullname" . }}-civo-webhook"
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-civo-webhook"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - civo.webhook.okteto.com
  resources:
  - civo
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ include "okteto.fullname" . }}-civo-webhook"
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-civo-webhook"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: "cert-manager"
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: "cert-manager-cainjector"
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: "cert-manager-webhook"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ include "okteto.fullname" . }}-civo-webhook"
  apiGroup: rbac.authorization.k8s.io
{{- end }}