apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "api"
    app.kubernetes.io/part-of: "okteto"
  name: "{{ include "okteto.fullname" . }}"
  namespace: {{ .Release.Namespace }}
data:
  "OKTETO_CONFIGMAP_NAME": "{{ include "okteto.fullname" . }}"
  "OKTETO_SERVICE_ACCOUNT_NAME": "{{ include "okteto.fullname" . }}"
  "OKTETO_VERSION": "{{ .Chart.Version }}"
  "OKTETO_CLOUD_PROVIDER": "{{ include "okteto.cloudProvider" . }}"
  "OKTETO_AUTH_PROVIDER": "{{ include "okteto.authProvider" . }}"
  "OKTETO_ADMIN_EMAIL": "{{ .Values.email }}"
  "OKTETO_ADMIN_CAN_DEPLOY": "{{ .Values.unsupported.adminCanDeploy }}"
  "OKTETO_RELEASE_NAME": "{{ .Release.Name }}"
  "OKTETO_MAINTENANCE": "{{ .Values.unsupported.maintenance }}"
  "CLUSTER_PUBLIC_ENDPOINT": "{{ .Values.cluster.endpoint }}"
  "OKTETO_APP_INSTALLER_CLUSTER_ROLE": "{{ include "okteto.fullname" . }}-app-installer"
  "OKTETO_APPLICATIONS_REPOSITORY": "{{ .Values.applications.repository }}"
  "OKTETO_QUICKSTARTS": {{ .Values.quickstarts | toJson | quote }}
  "OKTETO_SSH_SECRET_NAME": "{{ .Values.installer.sshSecretName }}"
  "OKTETO_PULL_POLICY": "{{ .Values.pullPolicy }}"
  "OKTETO_BASE_DOMAIN": "{{ .Values.subdomain }}"
  "OKTETO_DEV_CLUSTER_ROLE": "{{ default (include "okteto.devclusterrole" .) .Values.clusterRole }}"
  "OKTETO_SHOW_VOLUMES_ENABLED": "{{ .Values.unsupported.showVolumes }}"
  "OKTETO_FORCE_PODS_IN_VOLUME_ZONE": "{{ .Values.unsupported.forcePodsInVolumeZone }}"
  "OKTETO_POD_SECURITY_POLICY": "{{ include "okteto.fullname" . }}-restrictive"
  "OKTETO_PUBLIC_URL": "{{ include "okteto.public" . }}"
  "OKTETO_USER_DEFINED_NAMESPACES": "{{ .Values.userDefinedNamespaces }}"
  "OKTETO_INGRESS_RELOAD_DELAY": "{{ .Values.unsupported.ingressReloadDelay }}"
  "OKTETO_VIRTUAL_SERVICE_ENDPOINTS": "{{ .Values.unsupported.virtualServiceEndpoints }}"
  "OKTETO_INGRESS_CLASS": "{{ .Values.ingress.class }}"
  "OKTETO_INGRESS_FORCE_CLASS": "{{ .Values.ingress.forceIngressClass }}"
  "OKTETO_NAMESPACE_ANNOTATIONS": {{ .Values.namespace.annotations | toJson | quote }}
  "OKTETO_NAMESPACE_LABELS": {{ .Values.namespace.labels | toJson | quote }}
  "OKTETO_LOADBALANCER_CONVERSION_ENABLED": "{{ .Values.convertLoadBalancedServices.enabled }}"
  "OKTETO_COOKIE_HASH": "{{ .Values.cookie.hash }}"
  "OKTETO_DEFAULT_BACKEND": "{{ .Release.Name }}-ingress-nginx-defaultbackend.{{ .Release.Namespace }}"
  "OKTETO_BIN_IMAGE": "{{ .Values.backend.bin.image }}"
  "OKTETO_INSTALLER_IMAGE": "{{ .Values.backend.installer.image }}"
{{- if .Values.wildcardCertificate.privateCA.enabled }}
  "OKTETO_PRIVATECA_SECRET_NAME": "{{ .Values.wildcardCertificate.privateCA.secret.name }}"
  "OKTETO_PRIVATECA_SECRET_KEY": "{{ .Values.wildcardCertificate.privateCA.secret.key }}"
{{- end }}
{{- if .Values.telemetry.token }}
  "OKTETO_TELEMETRY_TOKEN": "{{ .Values.telemetry.token }}"
{{- end }}
  "OKTETO_TELEMETRY_ENABLED": "{{ .Values.telemetry.enabled }}"
{{- if and .Values.unsupported.injectDockerconfigInGitDeploys .Values.privateRegistry }}
  "OKTETO_DOCKERCONFIG_SECRET_NAME": "{{ include "okteto.fullname" . }}-dockerconfig"
{{- end}}
  "OKTETO_INJECT_DEV_BINARIES_ENABLED": "{{ .Values.injectDevelopmentBinaries.enabled }}"
{{- if .Values.auth.google.enabled }}
  "GOOGLE_CLIENTID": "{{ .Values.auth.google.clientId }}"
  "OKTETO_GOOGLE_ALLOW_DOMAINS": "{{ include "okteto.joinListWithComma" .Values.auth.google.allowDomains }}"
{{- else if .Values.auth.github.enabled }}
  "GITHUB_CLIENTID": "{{ .Values.auth.github.clientId }}"
  "GITHUB_ORGANIZATION": "{{ .Values.auth.github.organization }}"
  "OKTETO_GITHUB_ALLOW_LIST": "{{ include "okteto.joinListWithComma" .Values.auth.github.allowList }}"
{{- else if .Values.auth.bitbucket.enabled }}
  "BITBUCKET_CLIENTID": "{{ .Values.auth.bitbucket.clientId }}"
  "BITBUCKET_WORKSPACE": "{{ .Values.auth.bitbucket.workspace }}"
{{- else if .Values.auth.openid.enabled }}
  "OPENID_ISSUER": "{{ .Values.auth.openid.endpoints.issuer }}"
  "OPENID_CLIENTID": "{{ .Values.auth.openid.clientId }}"
  "OPENID_GROUP": "{{ .Values.auth.openid.group }}"
  "OPENID_MAPPING_EXTERNALID": "{{ .Values.auth.openid.mapping.externalIDKey }}"
  "OPENID_MAPPING_NAME": "{{ .Values.auth.openid.mapping.nameKey }}"
  "OPENID_MAPPING_EMAIL": "{{ .Values.auth.openid.mapping.emailKey }}"
  "OPENID_MAPPING_PICTURE": "{{ .Values.auth.openid.mapping.pictureKey }}"
  "OPENID_MAPPING_GROUPS": "{{ .Values.auth.openid.mapping.groupsKey }}"
{{- end}}
  "OKTETO_DEFAULT_PLAN": "{{ .Values.unsupported.defaultPlan }}"
  "OKTETO_POOL": "{{ .Values.tolerations.oktetoPool }}"
  "OKTETO_BUILD_POOL": "{{ .Values.tolerations.buildPool }}"
  "OKTETO_DEV_POOL": "{{ .Values.tolerations.devPool }}"
  "OKTETO_PROTECT_PERSONAL_NAMESPACE_ENABLED":  "{{ .Values.unsupported.protectPersonalNamespace }}"
  "OKTETO_PULLALWAYS_ENABLED":  "{{ .Values.pullAlways.enabled }}"
  "OKTETO_SERVICE_EXTERNAL_IPS_ENABLED":  "{{ .Values.externalIPs.enabled }}"
  "OKTETO_SERVICE_EXTERNAL_NAMES_ENABLED":  "{{ .Values.externalNames.enabled }}"
  "OKTETO_NETWORK_POLICIES_ENABLED":  "{{ .Values.networkPolicies.enabled }}"
{{- if .Values.networkPolicies.enabled }}
  "OKTETO_NETWORK_POLICIES_BLOCKED_CIDRS": {{ .Values.networkPolicies.blockedCIDRs | toJson | quote }}
{{- end }}
  "OKTETO_INGRESS_LIMITS_ENABLED":  "{{ .Values.ingressLimits.enabled }}"
{{- if .Values.ingressLimits.enabled }}
  "OKTETO_INGRESS_LIMITS_CONNECTIONS": "{{ .Values.ingressLimits.connections }}"
  "OKTETO_INGRESS_LIMITS_RPS": "{{ .Values.ingressLimits.rps }}"
  "OKTETO_INGRESS_LIMITS_RPM": "{{ .Values.ingressLimits.rpm }}"
{{- end }}
  "OKTETO_GC_ENABLED":  "{{ .Values.gc.enabled }}"
  "OKTETO_DEBUG_SERVER":  "{{ .Values.debugServer.enabled }}"
{{- if .Values.gc.enabled }}
  "OKTETO_GC_SCALE_TO_ZERO_PERIOD": "{{ .Values.gc.scaleToZeroPeriod }}"
  "OKTETO_GC_DELETE_NAMESPACE_PERIOD": "{{ .Values.gc.deleteNamespacePeriod }}"
{{- end }}
  "OKTETO_AUTOSCALER_ENABLED":  "{{ .Values.autoscaler.enabled }}"
{{- if .Values.autoscaler.enabled }}
  "OKTETO_AUTOSCALER_NODE_POOL_LABEL": "{{ .Values.autoscaler.nodePoolLabel }}"
  "OKTETO_AUTOSCALER_SCHEDULE": "{{ .Values.autoscaler.schedule }}"
  "OKTETO_AUTOSCALER_INCREMENT": "{{ .Values.autoscaler.increment }}"
  "OKTETO_AUTOSCALER_MIN": "{{ .Values.autoscaler.min }}"
  "OKTETO_AUTOSCALER_MAX": "{{ .Values.autoscaler.max }}"
  "OKTETO_AUTOSCALER_CPU_UP": "{{ or .Values.autoscaler.up .Values.autoscaler.cpu.up }}"
  "OKTETO_AUTOSCALER_CPU_DOWN": "{{ or .Values.autoscaler.down .Values.autoscaler.cpu.down  }}"
  "OKTETO_AUTOSCALER_MEMORY_UP": "{{ or .Values.autoscaler.up .Values.autoscaler.memory.up }}"
  "OKTETO_AUTOSCALER_MEMORY_DOWN": "{{ or .Values.autoscaler.down .Values.autoscaler.memory.down }}"
  "OKTETO_AUTOSCALER_PODS_UP": "{{ .Values.autoscaler.pods.up }}"
  "OKTETO_AUTOSCALER_PODS_DOWN": "{{ .Values.autoscaler.pods.down }}"
  "OKTETO_AUTOSCALER_VOLUMES_UP": "{{ .Values.autoscaler.volumes.up }}"
  "OKTETO_AUTOSCALER_VOLUMES_DOWN": "{{ .Values.autoscaler.volumes.down }}"
{{- end }}
  "OKTETO_VOLUME_SNAPSHOTS_ENABLED":  "{{ .Values.volumeSnapshots.enabled }}"
{{- if .Values.volumeSnapshots.enabled }}
  "OKTETO_VOLUME_SNAPSHOTS_DRIVER": "{{ .Values.volumeSnapshots.driver }}"
  "OKTETO_VOLUME_SNAPSHOTS_CLASS": "{{ .Values.volumeSnapshots.class }}"
  "OKTETO_VOLUME_SNAPSHOTS_STORAGE_CLASS": "{{ .Values.volumeSnapshots.storageClass }}"
{{- end }}
  "OKTETO_QUOTAS_RESOURCES_ENABLED":  "{{ .Values.quotas.resources.enabled }}"
{{- if .Values.quotas.resources.enabled }}
  "OKTETO_QUOTAS_RESOURCES_MAX_NAMESPACES": "{{ .Values.quotas.resources.maxNamespaces }}"
  "OKTETO_QUOTAS_RESOURCES_MAX_PODS": "{{ .Values.quotas.resources.maxPods }}"
  "OKTETO_QUOTAS_RESOURCES_MAX_SERVICES": "{{ .Values.quotas.resources.maxServices }}"
  "OKTETO_QUOTAS_RESOURCES_MAX_REPlICATION_CONTROLLERS": "{{ .Values.quotas.resources.maxReplicationControllers }}"
  "OKTETO_QUOTAS_RESOURCES_MAX_SECRETS": "{{ .Values.quotas.resources.maxSecrets }}"
  "OKTETO_QUOTAS_RESOURCES_MAX_CONFIGMAPS": "{{ .Values.quotas.resources.maxConfigMaps }}"
  "OKTETO_QUOTAS_RESOURCES_MAX_PVCS":  "{{ .Values.quotas.resources.maxPVCs }}"
  "OKTETO_QUOTAS_RESOURCES_MAX_VOLUME_SNAPSHOTS": "{{ .Values.quotas.resources.maxVolumeSnapshots }}"
{{- end }}
  "OKTETO_QUOTAS_BANDWIDTH_ENABLED":  "{{ .Values.quotas.bandwidth.enabled }}"
{{- if .Values.quotas.bandwidth.enabled }}
  "OKTETO_QUOTAS_BANDWIDTH_INGRESS": "{{ .Values.quotas.bandwidth.ingress }}"
  "OKTETO_QUOTAS_BANDWIDTH_EGRESS": "{{ .Values.quotas.bandwidth.egress }}"
{{- end }}
  "OKTETO_QUOTAS_REQUESTS_ENABLED":  "{{ .Values.quotas.requests.enabled }}"
  "OKTETO_AUTOSET_DEFAULT_LIMITS":  "{{ .Values.unsupported.autoSetDefaultLimits }}"
{{- if .Values.quotas.requests.enabled }}
  "OKTETO_QUOTAS_REQUESTS_CPU": "{{ .Values.quotas.requests.cpu }}"
  "OKTETO_QUOTAS_REQUESTS_MEMORY": "{{ .Values.quotas.requests.memory }}"
  "OKTETO_QUOTAS_REQUESTS_STORAGE": "{{ .Values.quotas.requests.storage }}"
{{- end }}
  "OKTETO_QUOTAS_LIMITS_ENABLED":  "{{ .Values.quotas.limits.enabled }}"
{{- if .Values.quotas.limits.enabled }}
  "OKTETO_QUOTAS_LIMITS_CPU": "{{ .Values.quotas.limits.cpu }}"
  "OKTETO_QUOTAS_LIMITS_MEMORY": "{{ .Values.quotas.limits.memory }}"
  "OKTETO_QUOTAS_LIMITS_STORAGE": "{{ .Values.quotas.limits.storage }}"
{{- end }}
  "OKTETO_QUOTAS_LIMITRANGES_MAX_ENABLED":  "{{ .Values.quotas.limitranges.max.enabled }}"
{{- if .Values.quotas.limitranges.max.enabled }}
  "OKTETO_QUOTAS_LIMITRANGES_MAX_CPU": "{{ .Values.quotas.limitranges.max.cpu }}"
  "OKTETO_QUOTAS_LIMITRANGES_MAX_MEMORY": "{{ .Values.quotas.limitranges.max.memory }}"
{{- end }}
  "OKTETO_QUOTAS_LIMITRANGES_REQUESTS_ENABLED":  "{{ .Values.quotas.limitranges.requests.enabled }}"
{{- if .Values.quotas.limitranges.requests.enabled }}
  "OKTETO_QUOTAS_LIMITRANGES_LIMIT_REQUEST_RATIO":  "{{ .Values.quotas.limitranges.requests.limitRequestRatio }}"
  "OKTETO_QUOTAS_LIMITRANGES_REQUESTS_CPU": "{{ .Values.quotas.limitranges.requests.cpu }}"
  "OKTETO_QUOTAS_LIMITRANGES_REQUESTS_MEMORY": "{{ .Values.quotas.limitranges.requests.memory }}"
{{- end }}
  "OKTETO_QUOTAS_LIMITRANGES_LIMITS_ENABLED":  "{{ .Values.quotas.limitranges.limits.enabled }}"
{{- if .Values.quotas.limitranges.limits.enabled }}
  "OKTETO_QUOTAS_LIMITRANGES_LIMITS_CPU": "{{ .Values.quotas.limitranges.limits.cpu }}"
  "OKTETO_QUOTAS_LIMITRANGES_LIMITS_MEMORY": "{{ .Values.quotas.limitranges.limits.memory }}"
{{- end }}
{{- if .Values.registry.enabled }}
  "OKTETO_REGISTRY_URL": "{{ include "okteto.registry"  . }}"
  "OKTETO_REGISTRY_PULLPOLICY": "{{ .Values.registry.pullPolicy }}"
{{- end }}
{{- if .Values.buildkit.enabled }}
  "OKTETO_BUILDKIT_URL": "tcp://{{ include "okteto.buildkit"  . }}:1234"
  "OKTETO_BUILDKIT_ENDPOINT_NAME": "{{ include "okteto.fullname" . }}-buildkit"
{{- end }}
{{- if .Values.unsupported.billing.enabled }}
  "OKTETO_BILLING_PLAN": "{{ .Values.unsupported.billing.plan }}"
  "OKTETO_CRM_TRIAL_STARTED": "{{ .Values.unsupported.billing.crm.trialStarted }}"
  "OKTETO_CRM_TRIAL_EXPIRED": "{{ .Values.unsupported.billing.crm.trialExpired }}"
{{- end }}
{{- if .Values.unsupported.opentracing.enabled }}
  "JAEGER_AGENT_HOST": "{{ .Values.unsupported.opentracing.agent.host }}"
  "JAEGER_AGENT_PORT": "{{ .Values.unsupported.opentracing.agent.port }}"
  "JAEGER_SAMPLER_TYPE": "{{ .Values.unsupported.opentracing.sampler.type }}"
  "JAEGER_SAMPLER_PARAM": "{{ .Values.unsupported.opentracing.sampler.param }}"
{{- end}}
{{- if .Values.unsupported.mailgun.enabled }}
  "MG_DOMAIN": "{{ .Values.unsupported.mailgun.domain }}"
{{- end }}
{{- if .Values.unsupported.privateEndpointsOverride.enabled }}
  "OKTETO_PRIVATE_ENDPOINTS": "https://{{ include "okteto.privateEndpoints" . }}"
  "PRIVATE_ENDPOINTS_CLIENTID": "{{ .Values.unsupported.privateEndpointsOverride.clientId }}"
{{- end }}
  "OKTETO_GITHUB_INTEGRATION_ENABLED": "{{ .Values.github.enabled }}"
{{- if .Values.github.enabled }}
  "GITHUB_INTEGRATION_CLIENTID": "{{ .Values.github.clientId }}"
  "GITHUB_INTEGRATION_APP_ID": "{{ .Values.github.appId }}"
  "GITHUB_INTEGRATION_INSTALLATION_URL": "{{ .Values.github.installationUrl }}"
{{- end }}
  "OKTETO_NODE_READINESS_CHECKER_ENABLED":  "{{ .Values.nodeReadinessChecker.enabled }}"
{{- if .Values.nodeReadinessChecker.enabled }}
  "OKTETO_NODE_READINESS_COMPONENTS": "{{ include "okteto.joinListWithComma" .Values.nodeReadinessChecker.components }}"
{{- end}}
  "OKTETO_MAX_PERSONAL_ACCESS_TOKEN": "{{ .Values.store.personalAccessToken.max }}"
  "OKTETO_GCP_STORE_ENABLED": "{{ .Values.store.provider.gcp.enabled }}"
  "OKTETO_GIT_SSH_USER": "{{ .Values.installer.gitSSHUser }}"
  "OKTETO_EXTERNAL_ACCOUNT_MINIMUM_CREATION_DAYS": "{{ .Values.unsupported.signupRestrictions.externalAccountMinimumCreationDays }}"
  "OKTETO_BANNED_SIGNUP_EMAIL_DOMAINS": "{{ include "okteto.joinListWithComma" .Values.unsupported.signupRestrictions.bannedEmailDomains }}"
  "OKTETO_DEV_STORAGE_CLASS_ENABLED": "{{ .Values.devStorageClass.enabled }}"
{{- if .Values.devStorageClass.enabled }}
  "OKTETO_DEFAULT_DEV_STORAGE_CLASS": "{{ .Values.devStorageClass.storageClass }}"
{{- end}}
  "OKTETO_NODE_STATIC_IP_ENABLED": "{{ .Values.unsupported.staticIPs }}"
  "OKTETO_VALIDATE_PVC_ENABLED": "{{ .Values.volumes.validate.enabled }}"
{{- if .Values.volumes.validate.enabled }}
  "OKTETO_SUPPORTED_STORAGE_CLASSES": "{{ include "okteto.joinListWithComma" .Values.volumes.validate.supportedStorageClasses }}"
  "OKTETO_FORCE_STORAGE_CLASS": "{{ .Values.volumes.validate.forceStorageClass }}"
  "OKTETO_SUPPORTED_ACCESS_MODES": "{{ include "okteto.joinListWithComma" .Values.volumes.validate.supportedAccessModes }}"
{{- end}}
  "OKTETO_GIT_INSTALLER_ACTIVE_DEADLINE_SECONDS": "{{ .Values.installer.activeDeadlineSeconds }}"
  "OKTETO_AUTO_ADMIN_ENABLED": "{{ .Values.autoAdmin.enabled }}"
  "OKTETO_SCALE_DOWN_PERSISTENT_RESOURCES": "{{ .Values.unsupported.scaleDownPersistentResources }}"
  "OKTETO_NAMESPACE_DESTROY_ALL_JOB_IMAGE": "{{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}"
  "OKTETO_NAMESPACE_DESTROY_ALL_ENABLED": "{{ .Values.namespaceDestroyAll.enabled }}"
{{- if .Values.unsupported.metrics.enabled}}
  "OKTETO_METRICS_URL": "{{ .Values.unsupported.metrics.url }}"
  "OKTETO_METRICS_HEADERS": {{ .Values.unsupported.metrics.headers | toJson | b64enc | quote }}
  "OKTETO_METRICS_EVENTS": {{ .Values.unsupported.metrics.events | toJson | b64enc | quote }}
{{- end}}
  "OKTETO_LOGS_BY_STAGE_ENABLED": "{{ .Values.unsupported.logsByStage.enabled }}"
  "OKTETO_TEAMS_ENABLED": "{{ .Values.unsupported.teams.enabled }}"
  "OKTETO_USER_SETTINGS_ENABLED": "{{ .Values.unsupported.userSettings.enabled }}"
  "OKTETO_AUTOMATIC_PREVIEWS_ENABLED": "{{ .Values.unsupported.automaticPreviews.enabled }}"
