apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "okteto.devclusterrole" . }}
  labels:
    app.kubernetes.io/name: {{ include "okteto.devclusterrole" . }}
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - "weaver.okteto.com"
  resources:
  - "diverts"
  verbs:
  - '*'
- apiGroups:
  - "git.okteto.com"
  resources:
  - "actions"
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - pods/exec
  - pods/attach
  - pods/portforward
  - pods/status
  - configmaps
  - secrets
  - services
  - serviceaccounts
  - persistentvolumeclaims
  - replicationcontrollers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - endpoints
  - events
  - limitranges
  - namespaces
  - namespaces/status
  - resourcequotas
  - resourcequotas/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  - deployments/scale
  - replicasets/scale
  - statefulsets/scale
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  - jobs/status
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - deployments
  - ingresses
  - replicasets
  - deployments/scale
  - replicasets/scale
  verbs:
  - '*'
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - policy
  resourceNames:
  - "{{ include "okteto.fullname" . }}-restrictive"
  resources:
  - podsecuritypolicies
  verbs:
  - use
- apiGroups:
    - apiextensions.k8s.io
  resources:
    - customresourcedefinitions
  verbs:
    - list
    - watch
- apiGroups:
    - helm.fluxcd.io
  resources:
    - helmreleases
    - helmreleases/status
  verbs:
  - '*'
- apiGroups:
    - helm.integrations.flux.weave.works
  resources:
    - fluxhelmreleases
  verbs:
  - '*'
- apiGroups:
    - configuration.konghq.com
  resources:
    - kongplugins
    - kongconsumers
    - kongcredentials
    - kongingresses
    - tcpingresses
  verbs:
  - '*'
- apiGroups:
    - openfaas.com
  resources:
    - functions
  verbs:
  - '*'
- apiGroups:
    - litmuschaos.io
  resources:
    - chaosengines
    - chaosexperiments
    - chaosresults
  verbs:
  - '*'
- apiGroups:
    - argoproj.io
  resources:
    - cronworkflows
    - workflows
    - workflowtemplates
    - workfloweventbinding
  verbs:
  - '*'
- apiGroups:
    - cert-manager.io
  resources:
    - certificates
  verbs:
  - list
  - watch
  - get
