apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "okteto.fullname" . }}-gc"
  labels:
    app.kubernetes.io/component: "gc"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-gc"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  schedule: "{{ .Values.gc.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "gc"
        app.kubernetes.io/part-of: "okteto"
    spec:
      activeDeadlineSeconds: {{ .Values.gc.timeoutInSeconds }}
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "gc"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.gc.labels }}
{{ toYaml .Values.gc.labels | indent 12 }}
{{- end }}
{{- if or .Values.podAnnotations .Values.gc.annotations }}
          annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 12 }}
  {{- end }}
  {{- if .Values.gc.annotations }}
{{ toYaml .Values.gc.annotations | indent 12 }}
  {{- end }}
{{- end }}
        spec:
          serviceAccountName: {{ include "okteto.fullname" . }}
          {{- if .Values.tolerations.oktetoPool }}
          tolerations:
          - key: "okteto-node-pool"
            operator: "Equal"
            value: "{{ .Values.tolerations.oktetoPool }}"
            effect: "NoSchedule"
          nodeSelector:
            okteto-node-pool: "{{ .Values.tolerations.oktetoPool }}"
          {{- end }}
          volumes:
          - name: tls-certs
            secret:
              defaultMode: 420
              secretName: {{ include "okteto.ingress.tlsSecret" . }}
          restartPolicy: Never
          containers:
            - name: gc
              image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "gc" ]
              envFrom:
                - configMapRef:
                    name: "{{ include "okteto.fullname" . }}"
                - secretRef:
                    name: {{ include "okteto.fullname" . }}
                - secretRef:
                    name: "{{ .Values.cloud.secret.name }}"
                    optional: true
              volumeMounts:
                - name: tls-certs
                  mountPath: /run/secrets/tls
                  readOnly: true
