{{- $publicUrl := include "okteto.defaultpublic" . -}}
{{- $buildkitURL := include "okteto.buildkit" . -}}
{{- $fullname := include "okteto.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "okteto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "okteto.name" . }}
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/component: "api"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  tls:
  - hosts:
    - {{ $publicUrl }}
    secretName: {{ include "okteto.ingress.tlsSecret" . }}
  rules:
  {{- range tuple $publicUrl $buildkitURL "localhost" }}
    - host: {{ . }}
      http:
        paths:
          {{- range tuple "/healthz" "/github" "/graphql" "/auth" "/deploy" "/sse" "/preview-environments" }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-api
                port:
                  number: {{ $.Values.api.port }}
          {{- end }}

          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: {{ $fullname }}-frontend
                port:
                  number: {{ $.Values.frontend.port }}
    {{- end }}
