{{- if .Values.unsupported.metricserverRbac }}
{{- if .Values.unsupported.metricserverRbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-server-psp
  namespace: kube-system
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - nodes
      - nodes/stats
      - namespaces
      - configmaps
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - policy
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - gce.privileged
    verbs:
      - use
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metrics-server-psp
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metrics-server-psp
subjects:
  - kind: ServiceAccount
    name: metrics-server
    namespace: kube-system
{{- end }}
{{- end }}