{{- if .Values.nodeReadinessChecker.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "okteto.fullname" . }}-nodes-readiness"
  labels:
    app.kubernetes.io/component: "nodes-readiness"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-nodes-readiness"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 30
  schedule: "{{ .Values.nodeReadinessChecker.schedule }}"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "nodes-readiness"
        app.kubernetes.io/part-of: "okteto"
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "nodes-readiness"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.podAnnotations  }}
          annotations:
{{ toYaml .Values.podAnnotations | indent 12 }}
{{- end }}
        spec:
          serviceAccountName: {{ include "okteto.fullname" . }}
          {{- if .Values.tolerations.oktetoPool }}
          tolerations:
          - key: "okteto-node-pool"
            operator: "Equal"
            value: "{{ .Values.tolerations.oktetoPool }}"
            effect: "NoSchedule"
          nodeSelector:
            okteto-node-pool: "{{ .Values.tolerations.oktetoPool }}"
          {{- end }}
          restartPolicy: Never
          containers:
            - name: nodes-readiness
              image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "nodes-readiness" ]
              envFrom:
                - configMapRef:
                    name: "{{ include "okteto.fullname" . }}"
                - secretRef:
                    name: {{ include "okteto.fullname" . }}
{{- end }}