apiVersion: v1
kind: Secret
metadata:
  name: {{ include "okteto.fullname" . }}
  labels:
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: "api"
    app.kubernetes.io/part-of: "okteto"
    {{- if .Values.secret.labels }}
{{ toYaml .Values.secret.labels | indent 4 }}
    {{- end }}
  {{- if .Values.secret.annotations }}
  annotations:
{{ toYaml .Values.secret.annotations | indent 4 }}
  {{- end }}
type: Opaque
data:
  "OKTETO_LICENSE": {{ default "" .Values.license | b64enc | quote }}
  "OKTETO_COOKIE_SECRET": {{ default "" .Values.cookie.secret | b64enc | quote  }}
  {{- if .Values.telemetry.planWebhook }}
  "OKTETO_PLAN_UPDATE_WEBHOOK": {{ .Values.telemetry.planWebhook | b64enc | quote }}
  {{- end }}
  {{- if .Values.telemetry.activityWebhook }}
  "OKTETO_ACTIVITY_WEBHOOK": {{ .Values.telemetry.activityWebhook | b64enc | quote }}
  {{- end }}
  {{- if .Values.telemetry.deleteUserWebhook }}
  "OKTETO_DELETE_USER_WEBHOOK": {{ .Values.telemetry.deleteUserWebhook | b64enc | quote }}
  {{- end }}
  {{- if and .Values.gc.enabled .Values.gc.slackWebhook }}
  "OKTETO_GC_SLACK_WEBHOOK": {{ .Values.gc.slackWebhook | b64enc | quote }}
  {{- end }}
  {{- if and .Values.autoscaler.enabled .Values.autoscaler.slackWebhook }}
  "OKTETO_AUTOSCALER_SLACK_WEBHOOK": {{ .Values.autoscaler.slackWebhook | b64enc | quote }}
  {{- end }}
  {{- if .Values.nodeReadinessChecker.slackWebhook }}
  "OKTETO_NODE_READINESS_SLACK_WEBHOOK": {{ .Values.nodeReadinessChecker.slackWebhook | b64enc | quote }}
  {{- end }}
  {{- if .Values.telemetry.signupBlockedWebhook }}
  "SIGNUP_BLOCKED_WEBHOOK": {{ .Values.telemetry.signupBlockedWebhook | b64enc | quote }}
  {{- end }}
  {{- if .Values.telemetry.updateEmailErrorWebhook }}
  "OKTETO_UPDATE_EMAIL_ERROR_WEBHOOK": {{ .Values.telemetry.updateEmailErrorWebhook | b64enc | quote }}
  {{- end }}
  {{- if .Values.unsupported.billing.enabled }}
  "OKTETO_BILLING_APIKEY": {{ default "" .Values.unsupported.billing.apiKey | b64enc | quote }}
  "OKTETO_BILLING_WHSECRET": {{ default "" .Values.unsupported.billing.whSecret | b64enc | quote }}
  "OKTETO_CRM_API": {{ default "" .Values.unsupported.billing.crm.apiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.unsupported.privateEndpointsOverride.enabled }}
  "PRIVATE_ENDPOINTS_CLIENTSECRET": {{ .Values.unsupported.privateEndpointsOverride.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.github.enabled }}
  "GITHUB_INTEGRATION_CLIENTSECRET": {{ .Values.github.clientSecret | b64enc | quote }}
  "GITHUB_APP_PRIVATE_KEY": {{ .Values.github.appPrivateKey | b64enc | quote }}
  {{- end }}
  {{- if (and .Values.auth.google.enabled .Values.auth.google.clientSecret) }}
  "GOOGLE_CLIENTSECRET": {{ .Values.auth.google.clientSecret | b64enc | quote }}
  {{- else if (and .Values.auth.github.enabled .Values.auth.github.clientSecret)}}
  "GITHUB_CLIENTSECRET": {{ .Values.auth.github.clientSecret | b64enc | quote }}
  {{- else if (and .Values.auth.bitbucket.enabled .Values.auth.bitbucket.clientSecret)}}
  "BITBUCKET_CLIENTSECRET": {{ .Values.auth.bitbucket.clientSecret | b64enc | quote }}
  {{- else if (and .Values.auth.openid.enabled .Values.auth.openid.clientSecret)}}
  "OPENID_CLIENTSECRET": {{ .Values.auth.openid.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.unsupported.mailgun.enabled }}
  "MG_API_KEY": {{ .Values.unsupported.mailgun.apiKey | b64enc | quote }}
  {{- end }}
  "GITHUB_WEBHOOK_SECRET": {{ default "" .Values.github.webhookSecret | b64enc | quote }}
