{{- if .Values.auth.token.enabled }}
{{- $serviceName := include "okteto.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceName }}-super-admin
  labels:
    app: {{ $serviceName }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    dev.okteto.com: "true"
  {{ if .Values.adminToken }}
    dev.okteto.com/token: "{{ .Values.adminToken }}"
  {{ else }}
    dev.okteto.com/token: "{{ randAlphaNum 40 }}"
  {{ end }}
  annotations:
    dev.okteto.com/super: "true"
{{- end }}
