{{- if .Values.telemetry.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: "{{ include "okteto.fullname" . }}-telemetry"
  labels:
    app.kubernetes.io/component: "telemetry"
    app.kubernetes.io/part-of: "okteto"
    app.kubernetes.io/name: "{{ include "okteto.fullname" . }}-telemetry"
    helm.sh/chart: {{ include "okteto.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "@daily"
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/component: "telemetry"
        app.kubernetes.io/part-of: "okteto"
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/component: "telemetry"
            app.kubernetes.io/part-of: "okteto"
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 12 }}
{{- end }}
{{- if .Values.telemetry.labels }}
{{ toYaml .Values.telemetry.labels | indent 12 }}
{{- end }}
{{- if or .Values.telemetry.annotations .Values.podAnnotations }}
          annotations:
  {{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 12 }}
  {{- end }}
  {{- if .Values.telemetry.annotations }}
{{ toYaml .Values.telemetry.annotations | indent 12 }}
  {{- end }}
{{- end }}
        spec:
          serviceAccountName: {{ include "okteto.fullname" . }}
          restartPolicy: Never
          containers:
            - name: telemetry
              image: {{ .Values.backend.image.registry }}:{{ .Values.backend.image.tag }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              args: [ "telemetry" ]
              envFrom:
                - configMapRef:
                    name: "{{ include "okteto.fullname" . }}"
                - secretRef:
                    name: {{ include "okteto.fullname" . }}
                - secretRef:
                    name: "{{ .Values.cloud.secret.name }}"
                    optional: true
              resources:
{{ toYaml .Values.telemetry.resources | indent 16 }}
{{- end}}