{{- if .Values.cloud.enabled }}
{{- if .Values.wildcardCertificate.create }}
{{- $wildcard := include "okteto.wildcard" . -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
 name: {{ .Values.wildcardCertificate.name }}
 labels:
   app.kubernetes.io/part-of: "okteto"
   app.kubernetes.io/component: "wildcard"
spec:
 secretName: {{ .Values.wildcardCertificate.name }}
 duration: {{ .Values.wildcardCertificate.duration }}
 renewBefore: 600h0m0s # 25d
 issuerRef:
  {{- if .Values.cloud.provider.byo.enabled }}
   name: {{ required "A valid .Values.cloud.provider.byo.issuerName is required" .Values.cloud.provider.byo.issuerName }}
  {{- else }}
   name: {{ include "okteto.fullname" . }}
  {{- end }}
   kind: {{ required "A valid .Values.cloud.provider.byo.issuerKind is required" .Values.cloud.provider.byo.issuerKind }}
 dnsNames:
   - "{{ $wildcard }}"
{{- end}}
{{- end}}