apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "valheim.fullname" . }}
  labels:
    app: {{ template "valheim.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "valheim.fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "valheim.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      {{- if .Values.valheimServer.nodeSelector }}
      {{- with .Values.valheimServer.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ template "valheim.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: SERVER_NAME
          value: {{ .Values.valheimServer.serverName | quote }}
        - name: SERVER_PORT
          value: {{ .Values.networking.gamePort | quote }}
        - name: WORLD_NAME
          value: {{ .Values.valheimServer.worldName | quote }}
        - name: SERVER_PASS
          value: {{ .Values.valheimServer.serverPass | quote }}
        - name: SERVER_PUBLIC
          value: {{ .Values.valheimServer.serverPublic | quote }}
        - name: UPDATE_INTERVAL
          value: {{ .Values.valheimServer.updateInterval | quote }}
        - name: BACKUPS_INTERVAL
          value: {{ .Values.valheimServer.backupsInterval | quote }}
        - name: BACKUPS_DIRECTORY
          value: {{ .Values.valheimServer.backupsDirectory | quote }}
        - name: BACKUPS_MAX_AGE
          value: {{ .Values.valheimServer.backupsMaxAge | quote }}
        - name: STATUS_HTTP
          value: {{ .Values.valheimServer.status | quote}}
        - name: STATUS_HTTP_PORT
          value: {{ .Values.networking.statusPort | quote}}
        - name: STEAMCMD_ARGS
          value: {{ .Values.valheimServer.steamArgs | quote }}

        {{- if eq .Values.valheimServer.mods.bepinex true }}
        - name: BEPINEX
          value: "true"
        {{- end }}
        {{- if eq .Values.valheimServer.mods.valheimPlus true }}
        - name: VALHEIMPLUS
          value: "true"
        {{- end }}
        
        ports:
        - containerPort: {{ .Values.networking.gamePort | int }}
          name: gameport
        - containerPort: {{ .Values.networking.gamePort | int | add 1 }}
          name: queryport
        - containerPort: {{ .Values.networking.statusPort | int }}
          name: statusport
        
        volumeMounts:
        - name: config
          mountPath: /config

      volumes:
      - name: config
        persistentVolumeClaim:
{{- if eq .Values.persistence.claimName "" }}
          claimName: {{ template "valheim.fullname" . }}-config
{{- else }}
          claimName: {{ .Values.persistence.claimName }}
{{- end }}
